/* ATLAS application logic — preserved from the validated build. */
'use strict';
const SUPABASE_URL='https://dwrrbpiprcmajfyronlf.supabase.co';
const SUPABASE_KEY='sb_publishable_akr0opK3RV0Mg5CQpF2woQ_hBFyRIJa';
const headers={apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`};
let skuData=[],locationRows=[],recentSkus=[];let toastTimer;
const $=id=>document.getElementById(id);const search=$('search'),clearBtn=$('clear'),suggestions=$('suggestions'),results=$('results'),emptyState=$('emptyState');
const escapeHtml=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const normalize=v=>String(v??'').toUpperCase().replace(/\s+/g,'').replace(/[^A-Z0-9-]/g,'');
function strictSkuMatch(sku,query){const source=normalize(sku),q=normalize(query);if(!q)return false;return q.split('-').filter(Boolean).every(part=>source.includes(part));}
async function fetchAll(table,select='*'){const pageSize=1000;let offset=0,all=[];while(true){const url=`${SUPABASE_URL}/rest/v1/${table}?select=${encodeURIComponent(select)}&order=created_at.asc&limit=${pageSize}&offset=${offset}`;const response=await fetch(url,{headers});if(!response.ok)throw new Error(`${table}: ${response.status}`);const page=await response.json();all=all.concat(page);if(page.length<pageSize)return all;offset+=pageSize;}}
function saveRecents(){localStorage.setItem('atlas-recent-skus',JSON.stringify(recentSkus));}
function loadRecents(){try{const stored=JSON.parse(localStorage.getItem('atlas-recent-skus')||'[]');recentSkus=Array.isArray(stored)?stored.slice(0,5):[];}catch{recentSkus=[];}}
function addRecent(sku){recentSkus=[sku,...recentSkus.filter(item=>item!==sku)].slice(0,5);saveRecents();renderRecents();}
function renderRecents(){const section=$('recentsSection'),list=$('recentList');if(!recentSkus.length){section.classList.add('hidden');list.innerHTML='';return;}section.classList.remove('hidden');list.innerHTML=recentSkus.map((sku,index)=>`<button class="recent-item" type="button" data-sku="${escapeHtml(sku)}"><span class="recent-clock"></span><span class="recent-copy"><strong>${escapeHtml(sku)}</strong><span>${index===0?'Most recent':'Recent search'}</span></span><span class="chevron">›</span></button>`).join('');list.querySelectorAll('[data-sku]').forEach(btn=>btn.addEventListener('click',()=>selectSku(btn.dataset.sku)));}
async function loadData(){try{const [skus,locations]=await Promise.all([fetchAll('skus'),fetchAll('locations')]);const skuById=new Map(skus.filter(s=>s.active!==false).map(s=>[s.id,s]));locationRows=locations.filter(l=>skuById.has(l.sku_id)).map(l=>({...l,sku:skuById.get(l.sku_id).sku}));skuData=[...skuById.values()].map(s=>({id:s.id,sku:s.sku,description:s.description||'',locations:locationRows.filter(l=>l.sku_id===s.id).sort((a,b)=>Number(a.aisle)-Number(b.aisle)||String(a.section).localeCompare(String(b.section)))})).sort((a,b)=>a.sku.localeCompare(b.sku));$('connectionStatus').textContent='LIVE';$('connectionStatus').className='connection live';renderAisles();}catch(error){console.error(error);$('connectionStatus').textContent='OFFLINE';$('connectionStatus').className='connection error';showEmpty('Could not load warehouse data',error.message,true);}}
function showSuggestions(query){if(!normalize(query)){suggestions.style.display='none';return;}const matches=skuData.filter(item=>strictSkuMatch(item.sku,query)).slice(0,12);suggestions.innerHTML=matches.map(item=>`<div class="suggestion" tabindex="0" data-sku="${escapeHtml(item.sku)}">${escapeHtml(item.sku)}<small>${item.locations.length} location${item.locations.length===1?'':'s'}${item.locations[0]?` · ${escapeHtml(locationLabel(item.locations[0]))}`:''}</small></div>`).join('');suggestions.style.display=matches.length?'block':'none';suggestions.querySelectorAll('.suggestion').forEach(el=>{el.addEventListener('click',()=>selectSku(el.dataset.sku));el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectSku(el.dataset.sku);}});});}
function isBackWall(section){return ['BACK WALL STORAGE','BACK WALL','BWS','REAR WALL STORAGE','REAR WALL','RWS'].includes(String(section??'').toUpperCase());}
function locationLabel(loc){if(Number(loc.aisle)===23)return `Samples Rack ${loc.section}`;return isBackWall(loc.section)?'BACK':`${loc.aisle}${loc.section}`;}
function locationTitle(loc){if(Number(loc.aisle)===23)return `Samples Rack · Section ${loc.section}`;return isBackWall(loc.section)?`Aisle ${loc.aisle} · Back Wall Storage`:`Aisle ${loc.aisle} · Section ${loc.section}`;}
function buildMap(loc){if(isBackWall(loc.section))return '';const active=String(loc.section||'').toUpperCase();return `<div class="map-panel"><div class="map-title"><strong>${Number(loc.aisle)===23?'Samples Rack':`Aisle ${escapeHtml(loc.aisle)}`} warehouse layout</strong><span>Selected: ${escapeHtml(active)}</span></div><div class="aisle-map"><div class="map-stack"><div class="map-section ${active==='A'?'active':''}">A</div><div class="drive-lane main">MAIN FORKLIFT DRIVEWAY</div><div class="map-section ${active==='B'?'active':''}">B</div><div class="drive-lane">FORKLIFT DRIVEWAY 2</div><div class="map-section ${active==='C'?'active':''}">C</div><div class="drive-lane">FORKLIFT DRIVEWAY 3</div><div class="map-section ${active==='D'?'active':''}">D</div></div><div class="orientation"><span>Front<br>of Aisle</span><span class="orientation-line"></span><span>Back<br>of Aisle</span></div></div></div>`;}
function showToast(message){const toast=$('toast');toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),1200);}
async function copySku(sku){try{await navigator.clipboard.writeText(sku);}catch{const area=document.createElement('textarea');area.value=sku;document.body.appendChild(area);area.select();document.execCommand('copy');area.remove();}showToast('✓ SKU copied');}
function showEmpty(title,message,isError=false){$('resultsArea').classList.add('hidden');$('emptyArea').classList.remove('hidden');emptyState.className=`empty${isError?' not-found':''}`;emptyState.innerHTML=`<strong>${escapeHtml(title)}</strong><div>${escapeHtml(message)}</div>`;}
function clearOutput(){$('resultsArea').classList.add('hidden');$('emptyArea').classList.add('hidden');results.innerHTML='';}
function renderResult(item){$('emptyArea').classList.add('hidden');$('resultsArea').classList.remove('hidden');if(!item.locations.length){results.innerHTML=`<article class="result-card"><div class="result-top"><strong>SEARCH RESULTS</strong><span>0 LOCATIONS FOUND</span></div><div class="result-body"><button class="sku-copy" type="button" data-copy-sku="${escapeHtml(item.sku)}"><span class="sku">${escapeHtml(item.sku)}</span><small>Tap SKU to copy</small></button><div class="empty not-found" style="margin-top:18px"><strong>No location assigned</strong><div>This SKU exists but needs a warehouse location.</div></div></div></article>`;bindCopy();return;}const [primary,...overflow]=item.locations;const all=[primary,...overflow];results.innerHTML=`<article class="result-card"><div class="result-top"><strong>SEARCH RESULTS</strong><span>${all.length} LOCATION${all.length===1?'':'S'} FOUND</span></div><div class="result-body"><div class="sku-row"><button class="sku-copy" type="button" data-copy-sku="${escapeHtml(item.sku)}"><span class="sku">${escapeHtml(item.sku)}</span><small>All levels (A1 – A4) · Tap to copy</small></button></div><div class="location-list">${all.map((loc,index)=>`<button class="location-button" type="button"><span class="location-badge">${escapeHtml(locationLabel(loc))}</span><span class="location-detail"><strong>${escapeHtml(locationTitle(loc))} · ${index===0?'Primary':'Additional'} Location</strong><span>${escapeHtml(loc.level_info||'All Levels')}${loc.notes?` · ${escapeHtml(loc.notes)}`:''}</span></span><span class="chevron">›</span></button>`).join('')}</div>${buildMap(primary)}</div></article>`;bindCopy();}
function bindCopy(){results.querySelectorAll('[data-copy-sku]').forEach(btn=>btn.addEventListener('click',()=>copySku(btn.dataset.copySku)));}
function selectSku(sku){const item=skuData.find(x=>x.sku===sku);if(!item)return;showView('homeView');search.value=sku;clearBtn.style.display='block';suggestions.style.display='none';renderResult(item);addRecent(item.sku);search.blur();window.scrollTo({top:0,behavior:'smooth'});}
function runSearch(){const q=search.value;clearBtn.style.display=q?'block':'none';showSuggestions(q);const exact=skuData.find(item=>normalize(item.sku)===normalize(q));if(exact)renderResult(exact);else if(!q)clearOutput();else clearOutput();}
function renderAisles(){const aisleNumbers=[...new Set(locationRows.map(l=>Number(l.aisle)))].filter(Number.isFinite).sort((a,b)=>a-b);const grid=$('aisleGrid');if(!aisleNumbers.length){grid.innerHTML='<div class="empty">No aisles loaded.</div>';return;}grid.innerHTML=aisleNumbers.map((aisle,index)=>`<button class="aisle-tile ${index===0?'active':''}" type="button" data-aisle="${aisle}">${aisle}</button>`).join('');const showAisle=aisle=>{grid.querySelectorAll('.aisle-tile').forEach(btn=>btn.classList.toggle('active',Number(btn.dataset.aisle)===aisle));const bySection={A:[],B:[],C:[],D:[]};locationRows.filter(l=>Number(l.aisle)===aisle).forEach(l=>{const section=String(l.section||'').toUpperCase();if(bySection[section])bySection[section].push(l);});$('aisles').innerHTML=`<div class="aisle-card"><div class="aisle-card-title"><span>AISLE ${aisle}</span><span>WAREHOUSE LAYOUT</span></div>${['A','B','C','D'].map(section=>{const rows=bySection[section].sort((a,b)=>a.sku.localeCompare(b.sku));return `<div class="section"><div class="section-head"><span class="section-loc">Section ${section}</span><span class="section-count">${rows.length} SKU${rows.length===1?'':'s'}</span></div>${rows.length?rows.map(row=>`<button class="sku-chip" type="button" data-sku="${escapeHtml(row.sku)}">${escapeHtml(row.sku)}</button>`).join(''):'<div style="color:var(--muted);font-size:12px">No SKUs assigned</div>'}</div>`;}).join('')}</div>`;$('aisles').querySelectorAll('[data-sku]').forEach(btn=>btn.addEventListener('click',()=>selectSku(btn.dataset.sku)));};grid.querySelectorAll('.aisle-tile').forEach(btn=>btn.addEventListener('click',()=>showAisle(Number(btn.dataset.aisle))));showAisle(aisleNumbers[0]);}
function showView(viewId){document.querySelectorAll('main>section').forEach(section=>section.classList.toggle('hidden',section.id!==viewId));document.querySelectorAll('.nav-button').forEach(btn=>btn.classList.toggle('active',btn.dataset.view===viewId));suggestions.style.display='none';search.blur();}
search.addEventListener('input',runSearch);search.addEventListener('focus',()=>{if(search.value)showSuggestions(search.value);});search.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();const exact=skuData.find(item=>normalize(item.sku)===normalize(search.value));const first=exact||skuData.find(item=>strictSkuMatch(item.sku,search.value));if(first)selectSku(first.sku);else if(search.value.trim()){showEmpty('SKU not found',`No match for “${search.value.trim()}”.`,true);suggestions.style.display='none';search.blur();}}});
clearBtn.addEventListener('mousedown',e=>e.preventDefault());clearBtn.addEventListener('click',()=>{search.value='';clearBtn.style.display='none';suggestions.style.display='none';clearOutput();search.blur();});
$('clearRecents').addEventListener('click',()=>{recentSkus=[];saveRecents();renderRecents();showToast('Recents cleared');});
$('browseShortcut').addEventListener('click',()=>showView('aisleView'));document.querySelectorAll('.nav-button').forEach(btn=>btn.addEventListener('click',()=>showView(btn.dataset.view)));
const backdrop=$('drawerBackdrop');$('menuButton').addEventListener('click',()=>backdrop.classList.add('open'));$('drawerClose').addEventListener('click',()=>backdrop.classList.remove('open'));backdrop.addEventListener('click',e=>{if(e.target===backdrop)backdrop.classList.remove('open');});document.querySelectorAll('[data-drawer-view]').forEach(btn=>btn.addEventListener('click',()=>{showView(btn.dataset.drawerView);backdrop.classList.remove('open');}));$('aboutButton').addEventListener('click',()=>{backdrop.classList.remove('open');showToast('ATLAS · Warehouse SKU Finder');});document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap'))suggestions.style.display='none';});
loadRecents();renderRecents();loadData();
