(function(){
  "use strict";

  const Delivery=window.AtlasCocDelivery;
  const root=document.getElementById("receiver-root");
  const PAGE_SIZE=8;
  const SORT_OPTIONS=[
    ["newest","Newest first"],["oldest","Oldest first"],
    ["customer-asc","Customer A–Z"],
  ];
  const SORT_VALUES=new Set(SORT_OPTIONS.map(([value])=>value));
  let credentials=null,activeDeliveries=[],completedDeliveries=[],selected=null,preview=false;
  let branchContext=null;
  let previewState={status:"idle",html:"",error:"",id:""};
  let revisionState=freshRevision();
  const workbookCache=new Map();
  let connection="reconnecting",pairing=null,pollTimer=null,subscription=null,lastSynced=null;
  const savedSort=readPreference("sort");
  let screen="inbox",search="",sort=SORT_VALUES.has(savedSort)?savedSort:"newest",page=1,total=0;
  let metrics={awaiting:0,receivedToday:0,completedToday:0},selectedIds=new Set(),openMenu=null,bulkMenu=false;
  let dialog=null,notice=null,loading=true,searchTimer=null,loadSequence=0;

  const esc=(value)=>String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
  const plural=(count,word)=>`${Number(count||0).toLocaleString()} ${word}${Number(count)===1?"":word==="box"?"es":"s"}`;
  const snapshot=(record)=>record?.report_snapshot||{};
  const recordById=(id)=>[selected,...activeDeliveries,...completedDeliveries].find((record)=>record?.id===id)||null;
  const officialFileName=(record,fallback="Official COC.xlsx")=>{const snap=snapshot(record);return window.AtlasCocExcel?.outputFileName?.(snap.customerName,snap.invoiceNumber,snap.ifNumber)||fallback};
  const submitterName=(record)=>record?.submitted_by_display_name||snapshot(record).employeeDisplayName||snapshot(record).employee||"—";
  const recordTotals=(record)=>{const pallets=snapshot(record).pallets||[];return{pallets:pallets.length,boxes:pallets.reduce((sum,pallet)=>sum+(pallet.lots||[]).reduce((n,lot)=>n+Number(lot.cases||0),0),0)}};
  const time=(value)=>value?new Date(value).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}):"—";
  const dateTime=(value)=>value?`${new Date(value).toLocaleDateString([],{month:"short",day:"numeric"})} · ${time(value)}`:"—";
  const dayStart=()=>{const date=new Date();date.setHours(0,0,0,0);return date.toISOString()};
  const selectedOnPage=()=>completedDeliveries.filter((item)=>selectedIds.has(item.id));
  function freshRevision(){return{step:"preview",loading:false,error:"",file:null,filePreviewHtml:"",candidate:null,currentRevision:null,revisions:[]}}
  function readPreference(key){try{return localStorage.getItem(`atlas-coc-receiver-${key}`)||""}catch{return""}}
  function writePreference(key,value){try{localStorage.setItem(`atlas-coc-receiver-${key}`,String(value))}catch{}}
  function icon(name){const paths={
    clipboard:'<path d="M9 5h6M9 9h6M9 13h4"/><path d="M9 3h6v3H9z"/><rect x="5" y="4" width="14" height="17" rx="2"/>',
    inbox:'<path d="M4 14h4l2 3h4l2-3h4"/><path d="M6 4h12l2 10v6H4v-6z"/>',
    check:'<path d="m6 12 4 4 8-9"/><circle cx="12" cy="12" r="9"/>',
    search:'<circle cx="11" cy="11" r="7"/><path d="m16 16 5 5"/>',
    download:'<path d="M12 3v12m0 0 4-4m-4 4-4-4"/><path d="M5 19h14"/>',
    archive:'<path d="M4 7h16v13H4zM3 3h18v4H3zM9 11h6"/>',
    restore:'<path d="M4 8v6h6"/><path d="M6 15a7 7 0 1 0 1-8l-3 3"/>',
    shield:'<path d="M12 3 5 6v5c0 5 3 8 7 10 4-2 7-5 7-10V6z"/><path d="m9 12 2 2 4-4"/>',
  };return `<svg aria-hidden="true" viewBox="0 0 24 24">${paths[name]||""}</svg>`}

  function pairingQrMarkup(){
    const svg=String(pairing?.qrSvg||"").trim();
    if(!/^<svg(?:\s|>)/i.test(svg))return '<span class="receiver-qr-fallback">Use the six-digit code above.</span>';
    return svg.replace(/^<svg\b/i,'<svg class="receiver-qr-symbol" role="img" aria-label="Pairing QR code"');
  }

  function branchCode(){return branchContext?.selectedWarehouse?.code||branchContext?.warehouse?.code||credentials?.warehouseCode||"CA"}
  function branchName(){return branchContext?.selectedWarehouse?.display_name||branchContext?.warehouse?.display_name||`${branchCode()} Warehouse`}
  function header(){return `<header class="receiver-head"><div class="receiver-atlas-lockup" aria-label="ATLAS Warehouse Management"><img src="../atlas-brand-mark-dark.svg?v=97" alt="" aria-hidden="true"><span><b>ATLAS</b><small>WAREHOUSE MANAGEMENT</small></span></div><div class="receiver-brand-title"><h1>${esc(branchCode())} COC RECEIVER</h1><p>${esc(branchName())}</p></div><div class="receiver-status ${connection==="connected"?"":"is-offline"}"><strong>● ${connection==="connected"?"CONNECTED · READY":connection==="reconnecting"?"RECONNECTING…":"OFFLINE"}</strong><small>Last synced ${lastSynced?time(lastSynced):"—"}</small></div></header>`}
  function pairingMarkup(){
    if(!Delivery.getAuthSession())return `<section class="receiver-pair"><span class="receiver-eyebrow">OFFICE COC STATION</span><h1>ATLAS sign-in required</h1><p>Use the name and password assigned to this office station.</p><button class="receiver-primary" data-action="sign-in">SIGN IN</button></section>`;
    if(!pairing)return `<section class="receiver-pair"><span class="receiver-eyebrow">OFFICE COC STATION</span><h1>Pair this computer</h1><p>This browser needs supervisor approval before it can receive compliance reports.</p><button class="receiver-primary" data-action="start-pairing">Create Pairing Code</button></section>`;
    return `<section class="receiver-pair"><span class="receiver-eyebrow">PAIRING REQUEST</span><h1>Approve on a warehouse phone</h1><p>Workflows → Office COC Receiver</p><div class="receiver-code">${esc(pairing.pairingCode)}</div><div class="receiver-qr">${pairingQrMarkup()}</div><p>Expires ${time(pairing.expiresAt)}</p><p>${esc(pairing.status||"Waiting for supervisor approval…")}</p></section>`;
  }
  function metricCard(kind,label,value,copy=""){return `<article class="receiver-metric is-${kind}"><i>${icon(kind==="awaiting"?"clipboard":kind==="received"?"inbox":"check")}</i><span><small>${label}</small><strong>${Number(value||0).toLocaleString()}</strong>${copy?`<b>${copy}</b>`:""}</span></article>`}
  function metricsMarkup(){return `<section class="receiver-metrics" aria-label="COC summary">${metricCard("awaiting","AWAITING",metrics.awaiting,"Requires office review")}${metricCard("received","RECEIVED TODAY",metrics.receivedToday)}${metricCard("completed","COMPLETED TODAY",metrics.completedToday)}</section>`}
  function incomingCard(record){const snap=snapshot(record),totals=recordTotals(record);return `<article class="receiver-incoming-card"><span class="receiver-new">NEW</span><dl><div><dt>Customer Name</dt><dd>${esc(snap.customerName||"—")}</dd></div><div><dt>IF Number</dt><dd>${esc(snap.ifNumber||"—")}</dd></div><div><dt>INV Number</dt><dd>${esc(snap.invoiceNumber||"—")}</dd></div></dl><p>${icon("clipboard")} ${plural(totals.pallets,"pallet")} <b>·</b> ${plural(totals.boxes,"box")}</p><p>${esc(submitterName(record))} <b>·</b> ${time(record.sent_at)}</p><button type="button" class="receiver-open-report" data-action="open" data-id="${esc(record.id)}">OPEN REPORT <span>→</span></button></article>`}
  function incomingMarkup(){return `<section class="receiver-incoming"><h2>INCOMING COCs</h2>${activeDeliveries.length?activeDeliveries.map(incomingCard).join(""):`<div class="receiver-ready-strip"><span>${icon("check")}</span><div><strong>No COCs are waiting</strong><small>The receiver is connected and ready for the next warehouse report.</small></div></div>`}</section>`}
  function sortOptions(){return SORT_OPTIONS.map(([value,label])=>`<option value="${value}" ${sort===value?"selected":""}>${label}</option>`).join("")}
  function backButton(action,label,extraClass=""){return `<button type="button" class="receiver-nav-back ${extraClass}" data-action="${esc(action)}"><span class="receiver-nav-back-icon" aria-hidden="true">←</span><span>${esc(label)}</span></button>`}
  function toolbarMarkup({archive=false}={}){const count=selectedIds.size;return `<div class="receiver-toolbar"><label class="receiver-search">${icon("search")}<input type="search" data-receiver-search value="${esc(search)}" placeholder="Search customer, invoice, or IF number" autocomplete="off"></label><label class="receiver-sort"><span class="sr-only">Sort reports</span><select data-receiver-sort>${sortOptions()}</select></label><div class="receiver-toolbar-actions">${archive?backButton("show-inbox","Back to COC Receiver","receiver-toolbar-back"):`<button type="button" class="receiver-outline" data-action="show-archive">VIEW ARCHIVE</button>`}<button type="button" class="receiver-outline ${archive?"is-restore":""}" data-action="${archive?"restore-selected":"archive-selected"}" ${count?"":"disabled"}>${archive?"RESTORE":"ARCHIVE"} SELECTED${count?` (${count})`:""}</button>${archive?"":`<div class="receiver-bulk-menu"><button type="button" class="receiver-icon-button" data-action="toggle-bulk-menu" aria-label="More archive actions" aria-expanded="${bulkMenu}">•••</button>${bulkMenu?`<div class="receiver-menu"><button type="button" data-action="archive-all">Archive all completed COCs</button></div>`:""}</div>`}</div></div>`}
  function rowMarkup(record,{archive=false}={}){const snap=snapshot(record),totals=recordTotals(record),checked=selectedIds.has(record.id),menu=openMenu===record.id;return `<tr class="${checked?"is-selected":""}"><td><input type="checkbox" data-select-id="${esc(record.id)}" aria-label="Select ${esc(snap.invoiceNumber||"COC")}" ${checked?"checked":""}></td><td data-label="Date completed"><span class="receiver-date-check">✓</span>${dateTime(record.office_completed_at)}${archive&&record.receiver_archived_at?`<small>Archived ${dateTime(record.receiver_archived_at)}</small>`:""}</td><td data-label="Customer"><strong>${esc(snap.customerName||"—")}</strong></td><td data-label="Invoice">${esc(snap.invoiceNumber||"—")}</td><td data-label="IF number">${esc(snap.ifNumber||"—")}</td><td data-label="Pallets / boxes">${plural(totals.pallets,"pallet")} · ${plural(totals.boxes,"box")}</td><td data-label="Actions"><div class="receiver-row-actions"><button type="button" class="receiver-view" data-action="open" data-id="${esc(record.id)}">VIEW</button><button type="button" class="receiver-small-action" data-action="download" data-id="${esc(record.id)}" aria-label="Download ${esc(snap.invoiceNumber||"COC")}">${icon("download")}</button><div class="receiver-row-menu"><button type="button" class="receiver-small-action" data-action="toggle-row-menu" data-id="${esc(record.id)}" aria-label="More actions" aria-expanded="${menu}">•••</button>${menu?`<div class="receiver-menu"><button type="button" data-action="${archive?"restore-one":"archive-one"}" data-id="${esc(record.id)}">${icon(archive?"restore":"archive")} ${archive?"Restore to Completed":"Archive COC"}</button></div>`:""}</div></div></td></tr>`}
  function pageButtons(){const pages=Math.max(1,Math.ceil(total/PAGE_SIZE)),start=Math.max(1,Math.min(page-2,pages-4)),end=Math.min(pages,start+4);let items=`<button type="button" data-action="page" data-page="${page-1}" ${page<=1?"disabled":""} aria-label="Previous page">‹</button>`;for(let number=start;number<=end;number+=1)items+=`<button type="button" data-action="page" data-page="${number}" class="${number===page?"is-active":""}">${number}</button>`;if(end<pages)items+=`<span>…</span>`;items+=`<button type="button" data-action="page" data-page="${page+1}" ${page>=pages?"disabled":""} aria-label="Next page">›</button>`;return items}
  function reportsPanel({archive=false}={}){const from=total?((page-1)*PAGE_SIZE)+1:0,to=Math.min(page*PAGE_SIZE,total),allChecked=completedDeliveries.length&&completedDeliveries.every((item)=>selectedIds.has(item.id)),dateHeading=sort==="oldest"?"DATE COMPLETED ↑":sort==="newest"?"DATE COMPLETED ↓":"DATE COMPLETED";return `<section class="receiver-report-panel"><div class="receiver-panel-title"><div><span class="receiver-eyebrow">${archive?"SECURE RECORD STORAGE":"OFFICE HISTORY"}</span><h2>${archive?"COC ARCHIVE":"COMPLETED COCs"}</h2><p>${archive?"Archived reports remain securely stored, downloadable, and restorable.":"Completed reports remain available until archived."}</p></div></div>${toolbarMarkup({archive})}<div class="receiver-table-wrap"><table><thead><tr><th><input type="checkbox" data-select-page aria-label="Select all reports on this page" ${allChecked?"checked":""}></th><th>${dateHeading}</th><th>CUSTOMER</th><th>INVOICE</th><th>IF NUMBER</th><th>PALLETS / BOXES</th><th>ACTIONS</th></tr></thead><tbody>${completedDeliveries.length?completedDeliveries.map((item)=>rowMarkup(item,{archive})).join(""):`<tr><td colspan="7"><div class="receiver-table-empty">${search?"No reports match this search.":archive?"No COCs have been archived.":"No completed COCs yet."}</div></td></tr>`}</tbody></table></div><footer class="receiver-pagination"><span>Showing ${from}–${to} of ${total.toLocaleString()} ${archive?"archived":"completed"} COCs</span><nav aria-label="Report pages">${pageButtons()}</nav></footer></section>`}
  function inboxMarkup(){return `<div class="receiver-shell">${header()}${metricsMarkup()}${incomingMarkup()}${reportsPanel()}</div>`}
  function archiveMarkup(){return `<div class="receiver-shell">${header()}<div class="receiver-archive-head">${backButton("show-inbox","Back to COC Receiver")}<div><span class="receiver-eyebrow">RETAINED RECORDS</span><h1>COC Archive</h1><p>Search, download, or restore any archived compliance report.</p></div></div>${reportsPanel({archive:true})}</div>`}
  function palletMarkup(record){return (snapshot(record).pallets||[]).map((pallet)=>`<section class="receiver-pallet"><h3>PALLET ${pallet.number}</h3>${(pallet.lots||[]).map((lot)=>`<div class="receiver-lot"><span><strong>${esc(lot.model)}</strong><small><i>LOT</i><b>${esc(lot.lot)}</b></small></span><b>${plural(Number(lot.cases||0),"box")} · ${(Number(lot.cases||0)*Number(lot.caseQuantity||0)).toLocaleString()} units</b></div>`).join("")}</section>`).join("")}
  function revisionProgress(step){const active={handoff:2,upload:3,review:4,success:5}[step]||1,labels=["Review","Edit","Upload","Confirm","Complete"];return `<ol class="receiver-revision-progress" aria-label="Official COC revision progress">${labels.map((label,index)=>`<li class="${index+1===active?"is-active":""} ${index+1<active?"is-complete":""}"><span>${index+1<active?"✓":index+1}</span><b>${label}</b></li>`).join("")}</ol>`}
  function revisionHeader(eyebrow,title,copy,badge=""){const snap=snapshot(selected);return `<section class="receiver-revision-head"><div><span class="receiver-eyebrow">${esc(eyebrow)}</span><h1>${esc(title)}</h1><p>${esc(copy||`${snap.customerName||"—"} · ${snap.invoiceNumber||"—"}`)}</p></div>${badge?`<strong>${esc(badge)}</strong>`:""}</section>`}
  function revisionHistory(){if((revisionState.revisions||[]).length<2)return"";return `<section class="receiver-revision-history"><h2>Revision History</h2><div class="receiver-table-wrap"><table><thead><tr><th>REVISION</th><th>SAVED</th><th>BY</th><th>REASON</th><th>STATUS</th></tr></thead><tbody>${revisionState.revisions.map((revision)=>`<tr><td><strong>Revision ${Number(revision.revisionNumber||1)}</strong></td><td>${dateTime(revision.approvedAt||revision.createdAt)}</td><td>${Number(revision.revisionNumber)===1?"Warehouse submission":"ATLAS user"}</td><td>${esc(revision.reason||"—")}</td><td><span class="receiver-revision-status ${revision.isCurrent?"is-current":""}">${revision.isCurrent?"CURRENT":revision.status==="PENDING"?"PENDING":"PRESERVED"}</span></td></tr>`).join("")}</tbody></table></div></section>`}
  function revisionHandoffMarkup(){const current=revisionState.currentRevision,fileName=current?.fileName||workbookCache.get(selected.id)?.fileName||"Official COC.xlsx";return `<div class="receiver-shell">${header()}${backButton("revision-cancel","Back to Official COC")}${revisionProgress("handoff")}${revisionHeader("REVISION WORKFLOW","Edit the Actual Workbook","Download the exact current XLSX, make the correction in Excel, then return the saved file to ATLAS.","ORIGINAL PRESERVED")}<section class="receiver-revision-panel"><div class="receiver-revision-file"><b>XLSX</b><span><strong>${esc(fileName)}</strong><small>Official COC · Revision ${Number(current?.revisionNumber||1)} · Exact stored workbook</small></span></div><div class="receiver-revision-steps"><article><i>1</i><h2>Open</h2><p>Download the XLSX and open it in Microsoft Excel.</p></article><article><i>2</i><h2>Edit & Save</h2><p>Correct the submitted values and save the workbook.</p></article><article><i>3</i><h2>Return</h2><p>Upload the saved XLSX for validation and final confirmation.</p></article></div><p class="receiver-revision-note"><strong>The current Official COC stays protected.</strong> It changes only after the revised workbook passes ATLAS validation and you confirm it.</p>${revisionState.error?`<p class="receiver-revision-error">${esc(revisionState.error)}</p>`:""}<div class="receiver-revision-actions"><button class="receiver-outline" type="button" data-action="revision-cancel">CANCEL</button><button class="receiver-primary" type="button" data-action="revision-download" data-id="${esc(selected.id)}" ${revisionState.loading?"disabled":""}>${revisionState.loading?"PREPARING WORKBOOK…":"DOWNLOAD & OPEN IN EXCEL"}</button></div></section></div>`}
  function revisionUploadMarkup(){const file=revisionState.file;return `<div class="receiver-shell">${header()}<button type="button" class="receiver-nav-back" data-action="revision-step" data-step="handoff"><span class="receiver-nav-back-icon" aria-hidden="true">←</span><span>Back to Edit Instructions</span></button>${revisionProgress("upload")}${revisionHeader("UPLOAD REVISED WORKBOOK","Return the Saved XLSX to ATLAS","Choose the file saved from Excel. ATLAS checks its structure and records each changed COC field.","FINAL CONFIRMATION REQUIRED")}<form class="receiver-revision-panel" data-revision-upload><label class="receiver-revision-upload ${file?"has-file":""}"><input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" data-revision-file><i>${file?"✓":"↑"}</i><strong>${esc(file?.name||"Choose Revised XLSX")}</strong><small>${file?`${Math.max(1,Math.round(file.size/1024)).toLocaleString()} KB · Ready to validate`:"Microsoft Excel workbook (.xlsx) · Maximum 5 MB"}</small><b>${file?"CHOOSE A DIFFERENT FILE":"SELECT REVISED WORKBOOK"}</b></label><div class="receiver-revision-fields"><label><span>Correction reason</span><select name="reason" required><option value="">Select a reason</option><option>Lot number corrected</option><option>Quantity corrected</option><option>Customer, invoice, or IF corrected</option><option>Model number corrected</option><option>Other correction</option></select></label><label><span>Revision note</span><textarea name="note" maxlength="500" placeholder="Briefly describe what was corrected"></textarea></label></div><p class="receiver-revision-error" data-revision-error role="alert">${esc(revisionState.error)}</p><div class="receiver-revision-actions"><button class="receiver-outline" type="button" data-action="revision-step" data-step="handoff">BACK</button><button class="receiver-primary" type="submit" ${!file||revisionState.loading?"disabled":""}>${revisionState.loading?"VALIDATING WORKBOOK…":"VALIDATE REVISED WORKBOOK"}</button></div></form></div>`}
  function revisionChanges(){const changes=Array.isArray(revisionState.candidate?.changes)?revisionState.candidate.changes:[],visible=changes.slice(0,12);return `<div class="receiver-revision-changes">${visible.map((change)=>`<article><small>${esc(change.label||change.reference||"COC field")}</small><span>${esc(change.before||"Blank")}</span><i>→</i><strong>${esc(change.after||"Blank")}</strong></article>`).join("")}${changes.length>visible.length?`<p>${changes.length-visible.length} additional changes are preserved in the audit history.</p>`:""}</div>`}
  function revisionReviewMarkup(){const candidate=revisionState.candidate,changes=Array.isArray(candidate?.changes)?candidate.changes:[];return `<div class="receiver-shell">${header()}<button type="button" class="receiver-nav-back" data-action="revision-step" data-step="upload"><span class="receiver-nav-back-icon" aria-hidden="true">←</span><span>Replace File</span></button>${revisionProgress("review")}${revisionHeader("FINAL WORKBOOK REVIEW",`Confirm Revision ${Number(candidate?.revisionNumber||2)}?`,"Review the exact uploaded workbook and every detected change before making it official.","VALIDATED XLSX")}<div class="receiver-revision-review"><div>${revisionState.filePreviewHtml}</div><aside><span class="receiver-eyebrow">DETECTED COC CHANGES</span><h2>${plural(changes.length,"field")} changed</h2>${revisionChanges()}<dl><div><dt>Reason</dt><dd>${esc(candidate?.reason||"—")}</dd></div><div><dt>Submitted by</dt><dd>${esc(Delivery.currentUser()?.user_metadata?.display_name||Delivery.currentUser()?.email||"Signed-in ATLAS user")}</dd></div><div><dt>File integrity</dt><dd>${esc(String(candidate?.sha256||"").slice(0,12))}…</dd></div></dl><p><strong>Final confirmation:</strong> These exact uploaded XLSX bytes will become the current Official COC.</p></aside></div>${revisionState.error?`<p class="receiver-revision-error">${esc(revisionState.error)}</p>`:""}<div class="receiver-revision-actions"><button class="receiver-outline" type="button" data-action="revision-step" data-step="upload">REPLACE FILE</button><button class="receiver-primary" type="button" data-action="revision-approve" ${revisionState.loading?"disabled":""}>${revisionState.loading?"SAVING REVISION…":`MAKE REVISION ${Number(candidate?.revisionNumber||2)} OFFICIAL`}</button></div></div>`}
  function revisionSuccessMarkup(){const current=revisionState.currentRevision||revisionState.candidate;return `<div class="receiver-shell">${header()}${revisionProgress("success")}<section class="receiver-revision-panel receiver-revision-success"><i>✓</i><span class="receiver-eyebrow">REVISION COMPLETE</span><h1>Revision ${Number(current?.revisionNumber||2)} Is Now Official</h1><p>The exact spreadsheet uploaded from Excel is now the current Official COC. Every previous approved workbook remains preserved in revision history.</p><strong>ACTUAL XLSX · REVISION ${Number(current?.revisionNumber||2)} · CURRENT</strong><div class="receiver-revision-actions"><button class="receiver-primary" data-action="download" data-id="${esc(selected.id)}">DOWNLOAD OFFICIAL COC</button><button class="receiver-outline" data-action="revision-return">VIEW OFFICIAL COC</button></div>${revisionHistory()}</section></div>`}
  function officialPreviewMarkup(){if(revisionState.step==="handoff")return revisionHandoffMarkup();if(revisionState.step==="upload")return revisionUploadMarkup();if(revisionState.step==="review")return revisionReviewMarkup();if(revisionState.step==="success")return revisionSuccessMarkup();const snap=snapshot(selected),revision=Number(revisionState.currentRevision?.revisionNumber||1),body=previewState.status==="ready"&&previewState.id===selected.id?previewState.html:previewState.status==="error"?`<div class="receiver-preview-status is-error"><strong>Preview unavailable</strong><p>${esc(previewState.error)}</p><button type="button" class="receiver-outline" data-action="view-official" data-id="${esc(selected.id)}">TRY AGAIN</button></div>`:`<div class="receiver-preview-status"><span class="receiver-preview-spinner" aria-hidden="true"></span><strong>Opening the Official COC…</strong><p>ATLAS is reading the actual XLSX workbook.</p></div>`;return `<div class="receiver-shell">${header()}${backButton("back-detail","Back to COC Overview")}<section class="receiver-preview-head"><span class="receiver-eyebrow">ACTUAL WORKBOOK · CURRENT</span><h1>Official COC</h1><p>${esc(snap.customerName||"—")} · ${esc(snap.invoiceNumber||"—")}</p><strong class="receiver-revision-badge">ACTUAL XLSX · REVISION ${revision}</strong></section>${body}${revisionState.error?`<p class="receiver-revision-error">Workbook editing is unavailable: ${esc(revisionState.error)}</p>`:""}<div class="receiver-preview-download"><button class="receiver-primary receiver-download" data-action="revision-begin" data-id="${esc(selected.id)}">EDIT IN EXCEL</button><button class="receiver-primary receiver-download" data-action="download" data-id="${esc(selected.id)}">DOWNLOAD OFFICIAL COC</button></div>${revisionHistory()}</div>`}
  function detailMarkup(){const record=selected,snap=snapshot(record),archived=Boolean(record.receiver_archived_at);return `<div class="receiver-shell">${header()}${backButton("back",screen==="archive"?"Back to COC Archive":"Back to COC Receiver")}<section class="receiver-detail"><div class="receiver-detail-head"><span class="receiver-eyebrow ${archived?"is-archived":""}">${archived?"ARCHIVED":record.status==="OFFICE_COMPLETED"?"COMPLETED":"RECEIVED"}</span><h1>${esc(snap.customerName||"—")}</h1><p>${esc(snap.invoiceNumber||"—")}</p></div><dl><div><dt>Invoice</dt><dd>${esc(snap.invoiceNumber||"—")}</dd></div><div><dt>IF Number</dt><dd>${esc(snap.ifNumber||"—")}</dd></div><div><dt>Sent by</dt><dd>${esc(submitterName(record))} · ${time(record.sent_at)}</dd></div><div><dt>Received</dt><dd>${dateTime(record.received_at)}</dd></div></dl>${palletMarkup(record)}<div class="receiver-actions"><div class="receiver-official-actions"><button class="receiver-view-official" data-action="view-official" data-id="${esc(record.id)}">VIEW OFFICIAL COC</button><button class="receiver-primary receiver-download" data-action="download" data-id="${esc(record.id)}">DOWNLOAD OFFICIAL COC</button></div>${record.status!=="OFFICE_COMPLETED"?`<button class="receiver-primary receiver-complete" data-action="complete" data-id="${esc(record.id)}">MARK COMPLETED ✓</button>`:archived?`<button class="receiver-primary receiver-restore" data-action="restore-one" data-id="${esc(record.id)}">RESTORE TO COMPLETED</button>`:`<button class="receiver-primary receiver-archive-action" data-action="archive-one" data-id="${esc(record.id)}">ARCHIVE COC</button>`}</div></section></div>`}
  function dialogMarkup(){if(!dialog)return"";const restore=dialog.type.startsWith("restore"),all=dialog.type==="archive-all",count=all?total:dialog.ids.length;return `<div class="receiver-dialog-backdrop" role="presentation"><section class="receiver-dialog" role="dialog" aria-modal="true" aria-labelledby="receiver-dialog-title"><span class="receiver-dialog-icon">${icon(restore?"restore":"archive")}</span><span class="receiver-eyebrow">${restore?"RESTORE COC":"ARCHIVE CONFIRMATION"}</span><h2 id="receiver-dialog-title">${restore?`Restore ${plural(count,"report")}?`:all?"Archive all completed COCs?":`Archive ${plural(count,"report")}?`}</h2><p>${restore?"The selected COC will return to the Completed COCs workspace.":"Archived COCs leave the active workspace but remain securely stored, downloadable, and restorable. Nothing is deleted."}</p><div><button type="button" class="receiver-dialog-cancel" data-action="close-dialog">Cancel</button><button type="button" class="receiver-primary" data-action="confirm-dialog">${restore?"RESTORE":"ARCHIVE"}</button></div></section></div>`}
  function noticeMarkup(){return notice?`<div class="receiver-notice is-${notice.tone||"success"}" role="status">${esc(notice.text)}</div>`:""}
  function retentionMarkup(){return credentials&&!selected?`<div class="receiver-retention">${icon("shield")}<span>COC records are retained securely. Archiving removes them from this workspace without deleting company records.</span></div>`:""}
  function render(){root.innerHTML=(!credentials?pairingMarkup():selected&&preview?officialPreviewMarkup():selected?detailMarkup():screen==="archive"?archiveMarkup():inboxMarkup())+retentionMarkup()+dialogMarkup()+noticeMarkup();window.requestAnimationFrame?.(()=>window.AtlasCocExcel?.fitOfficialWorkbookPreviews?.(root))}
  function renderBackgroundUpdate(){if(!(selected&&preview&&previewState.status==="ready"))render()}

  async function loadInbox(){
    if(!credentials)return;const sequence=++loadSequence;loading=true;
    try{
      const section=screen==="archive"?"archive":"completed";
      let [activeResult,listResult,metricResult]=await Promise.all([
        screen==="archive"?Promise.resolve({deliveries:[]}):Delivery.receiverInbox(credentials,{section:"active",withMeta:true}),
        Delivery.receiverInbox(credentials,{section,withMeta:true,page,pageSize:PAGE_SIZE,search,sort}),
        Delivery.receiverInbox(credentials,{section:"metrics",withMeta:true,dayStart:dayStart()}),
      ]);
      if(sequence!==loadSequence)return;
      const sent=(activeResult.deliveries||[]).filter((item)=>item.status==="SENT");
      if(sent.length){await Promise.all(sent.map((item)=>Delivery.acknowledgeDelivery(item.id,credentials)));activeResult=await Delivery.receiverInbox(credentials,{section:"active",withMeta:true})}
      activeDeliveries=activeResult.deliveries||[];completedDeliveries=listResult.deliveries||[];total=Number(listResult.total||0);
      metrics={awaiting:Number(metricResult.awaiting||activeDeliveries.length),receivedToday:Number(metricResult.receivedToday||0),completedToday:Number(metricResult.completedToday||0)};
      const pages=Math.max(1,Math.ceil(total/PAGE_SIZE));if(page>pages){page=pages;return loadInbox()}
      connection=navigator.onLine?"connected":"offline";lastSynced=new Date();selectedIds=new Set([...selectedIds].filter((id)=>completedDeliveries.some((item)=>item.id===id)));renderBackgroundUpdate();
    }catch(error){connection=navigator.onLine?"reconnecting":"offline";notice={tone:"error",text:error?.message||"The COC Receiver could not refresh."};renderBackgroundUpdate()}
    finally{loading=false}
  }
  async function startPairing(){try{branchContext=await Delivery.warehouseContext();pairing=await Delivery.createPairing();render();pollPairing()}catch(error){pairing={status:error.message||"Pairing could not start."};render()}}
  async function pollPairing(){if(!pairing?.pairingSessionId)return;for(let attempt=0;attempt<120&&!credentials;attempt+=1){await new Promise((resolve)=>setTimeout(resolve,2500));try{const result=await Delivery.pairingStatus(pairing.pairingSessionId);pairing={...pairing,...result};if(result.status==="PAIRED"){credentials=result.credentials;render();connect();return}render()}catch(error){pairing={...pairing,status:error.message};render();return}}}
  function connect(){clearInterval(pollTimer);subscription?.close?.();subscription=Delivery.subscribeToDeliveries({onChange:loadInbox,onState:(state)=>{connection=state;renderBackgroundUpdate()}});pollTimer=setInterval(()=>{Delivery.heartbeat(credentials).catch(()=>{});loadInbox()},15000);loadInbox()}
  function setScreen(next){screen=next;selected=null;preview=false;previewState={status:"idle",html:"",error:"",id:""};revisionState=freshRevision();selectedIds.clear();openMenu=null;bulkMenu=false;search="";page=1;render();loadInbox()}
  function showNotice(text,tone="success"){notice={text,tone};render();setTimeout(()=>{notice=null;render()},2600)}
  function openConfirmation(type,ids=[]){dialog={type,ids};openMenu=null;bulkMenu=false;render()}
  async function confirmDialog(){const pending=dialog;if(!pending)return;dialog=null;render();try{let result;if(pending.type.startsWith("restore"))result=await Delivery.restoreOfficeArchived(pending.ids,credentials);else result=await Delivery.archiveOfficeCompleted(pending.ids,credentials,{all:pending.type==="archive-all"});selected=null;selectedIds.clear();await loadInbox();showNotice(`${plural(result.updated||pending.ids.length,"COC")} ${pending.type.startsWith("restore")?"restored":"archived"}.`)}catch(error){showNotice(error?.message||"The archive could not be updated.","error")}}
  async function loadWorkbook(id){if(workbookCache.has(id))return workbookCache.get(id);const workbook=await Delivery.downloadOfficeWorkbook(id,credentials);workbook.fileName=officialFileName(recordById(id),workbook.fileName);workbookCache.set(id,workbook);return workbook}
  async function loadRevisionStatus(id){try{const result=await Delivery.cocWorkbookRevision("status",{deliveryId:id},branchCode());if(!selected||selected.id!==id)return;revisionState.currentRevision=result.currentRevision||null;revisionState.revisions=Array.isArray(result.revisions)?result.revisions:[];revisionState.error=""}catch(error){if(selected?.id===id)revisionState.error=revisionError(error,"Workbook revision history is unavailable.")}}
  async function openOfficialPreview(id){const recordId=id||selected?.id;if(!recordId)return;preview=true;revisionState=freshRevision();previewState={status:"loading",html:"",error:"",id:recordId};render();try{const [workbook]=await Promise.all([loadWorkbook(recordId),loadRevisionStatus(recordId)]);const html=await window.AtlasCocExcel.renderOfficialWorkbookPreview(workbook.blob);if(!selected||selected.id!==recordId||!preview)return;previewState={status:"ready",html,error:"",id:recordId}}catch(error){previewState={status:"error",html:"",error:error?.message||"The Official COC could not be opened.",id:recordId}}render()}
  function revisionError(error,fallback="The workbook revision could not be completed."){const raw=String(error?.message||error||"");const map=[[/ATLAS_AUTH_REQUIRED/i,"Sign in to ATLAS before revising an Official COC."],[/WAREHOUSE_ACCESS_DENIED/i,"This account cannot revise COCs from another warehouse."],[/COC_REVISION_HAS_NO_CHANGES/i,"No COC data changes were detected in the uploaded workbook."],[/COC_REVISION_REASON_REQUIRED/i,"Select a correction reason."],[/COC_REVISION_STATUS_NOT_EDITABLE/i,"Only a received or completed COC can be revised."],[/COC_REVISION_(?:XLSX_REQUIRED|XLSX_INVALID|FILE_INVALID)/i,"Select the revised Microsoft Excel .xlsx workbook."],[/COC_REVISION_(?:FILE_TOO_LARGE|WORKBOOK_TOO_COMPLEX)/i,"The revised workbook must be 5 MB or smaller and use the official COC structure."],[/COC_REVISION_(?:TEMPLATE_STRUCTURE_MISSING|TEMPLATE_LAYOUT_CHANGED|OFFICIAL_SHEET_REQUIRED)/i,"The file no longer matches the Official COC template. Start again from the current workbook."],[/COC_REVISION_HEADER_FIELDS_REQUIRED/i,"Customer, invoice, and IF number must remain populated."],[/COC_REVISION_DETAIL_ROWS_REQUIRED/i,"The revised workbook must contain at least one COC detail row."],[/COC_REVISION_EXTERNAL_CONTENT_NOT_ALLOWED/i,"External links, connections, and macros are not allowed."],[/COC_REVISION_NOT_PENDING/i,"This revision was already processed. Reopen the current Official COC."],[/Request failed \(404\)|COC_REQUEST_FAILED_404/i,"The Official COC revision service is not available yet."]];return map.find(([pattern])=>pattern.test(raw))?.[1]||fallback}
  async function blobToBase64(blob){const bytes=new Uint8Array(await blob.arrayBuffer()),parts=[];for(let offset=0;offset<bytes.length;offset+=0x8000)parts.push(String.fromCharCode(...bytes.subarray(offset,offset+0x8000)));return btoa(parts.join(""))}
  async function stageRevision(form){const file=revisionState.file,errorNode=form.querySelector("[data-revision-error]"),submit=form.querySelector('button[type="submit"]');if(!file){if(errorNode)errorNode.textContent="Select the revised XLSX file saved from Excel.";return}revisionState.loading=true;revisionState.error="";if(submit){submit.disabled=true;submit.textContent="VALIDATING WORKBOOK…"}try{const previewHtml=await window.AtlasCocExcel.renderOfficialWorkbookPreview(file);const result=await Delivery.cocWorkbookRevision("stage-revision",{deliveryId:selected.id,fileName:file.name,workbookBase64:await blobToBase64(file),reason:form.elements.reason.value,note:form.elements.note.value},branchCode());revisionState={...revisionState,step:"review",loading:false,error:"",candidate:result.candidate||null,filePreviewHtml:previewHtml};render();window.scrollTo({top:0,left:0,behavior:"auto"})}catch(error){revisionState.loading=false;revisionState.error=revisionError(error,"The revised workbook could not be validated.");if(errorNode)errorNode.textContent=revisionState.error;if(submit){submit.disabled=false;submit.textContent="VALIDATE REVISED WORKBOOK"}}}
  async function approveRevision(){const candidate=revisionState.candidate;if(!candidate?.id||revisionState.loading)return;revisionState.loading=true;revisionState.error="";render();try{const result=await Delivery.cocWorkbookRevision("approve-revision",{deliveryId:selected.id,revisionId:candidate.id},branchCode());workbookCache.delete(selected.id);const workbook=await loadWorkbook(selected.id),html=await window.AtlasCocExcel.renderOfficialWorkbookPreview(workbook.blob);previewState={status:"ready",html,error:"",id:selected.id};revisionState={...revisionState,step:"success",loading:false,error:"",currentRevision:result.approved||candidate,revisions:Array.isArray(result.revisions)?result.revisions:revisionState.revisions};render();window.scrollTo({top:0,left:0,behavior:"auto"})}catch(error){revisionState.loading=false;revisionState.error=revisionError(error,"The revision could not be made official.");render()}}
  async function download(button){
    button.disabled=true;
    try{
      const id=button.dataset.id;
      const suggestedName=officialFileName(recordById(id));
      let fileHandle=null;
      if(typeof window.showSaveFilePicker==="function"){
        try{
          fileHandle=await window.showSaveFilePicker({
            suggestedName,
            startIn:"desktop",
            types:[{
              description:"Excel Workbook",
              accept:{"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":[".xlsx"]},
            }],
            excludeAcceptAllOption:true,
          });
        }catch(error){
          if(error?.name==="AbortError")return;
        }
      }
      const workbook=await loadWorkbook(id);
      if(fileHandle){
        const writable=await fileHandle.createWritable();
        await writable.write(workbook.blob);
        await writable.close();
        showNotice("Official COC saved.");
      }else{
        window.AtlasCocStorage?.downloadBlob(workbook.blob,workbook.fileName);
      }
      return true;
    }catch(error){
      showNotice(error?.message||"The official COC could not be saved.","error");return false;
    }finally{
      button.disabled=false;
    }
  }

  root.addEventListener("click",async(event)=>{
    const button=event.target.closest("[data-action]");if(!button)return;const action=button.dataset.action,id=button.dataset.id;
    if(action==="sign-in")window.AtlasAuth?.open?.();
    if(action==="start-pairing")startPairing();
    if(action==="open"){selected=[...activeDeliveries,...completedDeliveries].find((item)=>item.id===id)||null;preview=false;previewState={status:"idle",html:"",error:"",id:""};revisionState=freshRevision();openMenu=null;render()}
    if(action==="back"){selected=null;preview=false;previewState={status:"idle",html:"",error:"",id:""};revisionState=freshRevision();render()}
    if(action==="view-official")await openOfficialPreview(id);
    if(action==="back-detail"){preview=false;revisionState=freshRevision();render()}
    if(action==="revision-begin"){revisionState={...revisionState,step:"handoff",error:"",file:null,candidate:null,filePreviewHtml:""};render();window.scrollTo({top:0,left:0,behavior:"auto"})}
    if(action==="revision-cancel"){revisionState={...revisionState,step:"preview",loading:false,error:"",file:null,candidate:null,filePreviewHtml:""};render();window.scrollTo({top:0,left:0,behavior:"auto"})}
    if(action==="revision-step"){revisionState={...revisionState,step:button.dataset.step||"preview",loading:false,error:""};render();window.scrollTo({top:0,left:0,behavior:"auto"})}
    if(action==="revision-download"){revisionState.loading=true;revisionState.error="";render();const liveButton=root.querySelector('[data-action="revision-download"]');const saved=await download(liveButton||button);revisionState={...revisionState,step:saved?"upload":"handoff",loading:false,error:saved?"":revisionState.error};render();window.scrollTo({top:0,left:0,behavior:"auto"})}
    if(action==="revision-approve")await approveRevision();
    if(action==="revision-return"){revisionState={...revisionState,step:"preview",loading:false,error:"",file:null,candidate:null,filePreviewHtml:""};render();window.scrollTo({top:0,left:0,behavior:"auto"})}
    if(action==="show-archive")setScreen("archive");
    if(action==="show-inbox")setScreen("inbox");
    if(action==="toggle-row-menu"){openMenu=openMenu===id?null:id;bulkMenu=false;render()}
    if(action==="toggle-bulk-menu"){bulkMenu=!bulkMenu;openMenu=null;render()}
    if(action==="archive-one")openConfirmation("archive-one",[id]);
    if(action==="restore-one")openConfirmation("restore-one",[id]);
    if(action==="archive-selected")openConfirmation("archive-selected",[...selectedIds]);
    if(action==="restore-selected")openConfirmation("restore-selected",[...selectedIds]);
    if(action==="archive-all")openConfirmation("archive-all",[]);
    if(action==="close-dialog"){dialog=null;render()}
    if(action==="confirm-dialog")confirmDialog();
    if(action==="page"){page=Math.max(1,Number(button.dataset.page||1));selectedIds.clear();render();loadInbox()}
    if(action==="download")download(button);
    if(action==="complete"){button.disabled=true;try{await Delivery.markOfficeCompleted(id,credentials);selected=null;await loadInbox();showNotice("COC marked completed.")}catch(error){button.disabled=false;showNotice(error?.message||"The report could not be completed.","error")}}
  });
  root.addEventListener("input",(event)=>{if(!event.target.matches("[data-receiver-search]"))return;search=event.target.value;page=1;selectedIds.clear();clearTimeout(searchTimer);searchTimer=setTimeout(loadInbox,260)});
  root.addEventListener("change",(event)=>{
    if(event.target.matches("[data-revision-file]")){const file=event.target.files?.[0]||null;revisionState.error="";if(file&&!/\.xlsx$/i.test(file.name)){revisionState.file=null;revisionState.error="Select a Microsoft Excel .xlsx workbook."}else if(file&&file.size>5*1024*1024){revisionState.file=null;revisionState.error="The revised workbook must be 5 MB or smaller."}else revisionState.file=file;render();return}
    if(event.target.matches("[data-receiver-sort]")){sort=event.target.value;writePreference("sort",sort);page=1;selectedIds.clear();render();loadInbox();return}
    if(event.target.matches("[data-select-id]")){event.target.checked?selectedIds.add(event.target.dataset.selectId):selectedIds.delete(event.target.dataset.selectId);render();return}
    if(event.target.matches("[data-select-page]")){if(event.target.checked)completedDeliveries.forEach((item)=>selectedIds.add(item.id));else completedDeliveries.forEach((item)=>selectedIds.delete(item.id));render()}
  });
  root.addEventListener("submit",(event)=>{if(!event.target.matches("[data-revision-upload]"))return;event.preventDefault();if(!event.target.reportValidity())return;stageRevision(event.target)});
  window.addEventListener("atlas-auth-changed",async()=>{credentials=null;branchContext=await Delivery.warehouseContext({force:true}).catch(()=>null);const verified=await Delivery.verifyReceiver().catch(()=>({paired:false}));credentials=verified.paired?verified.credentials:null;if(verified.warehouse)branchContext={...(branchContext||{}),warehouse:verified.warehouse};render();if(credentials)connect()});
  window.addEventListener("online",connect);window.addEventListener("offline",()=>{connection="offline";renderBackgroundUpdate()});
  (async()=>{branchContext=await Delivery.warehouseContext().catch(()=>null);const verified=await Delivery.verifyReceiver().catch(()=>({paired:false}));credentials=verified.paired?verified.credentials:null;if(verified.warehouse)branchContext={...(branchContext||{}),warehouse:verified.warehouse};render();if(credentials)connect()})();
})();
