(function(){
  "use strict";
  const Delivery=window.AtlasCocDelivery;
  const root=document.getElementById("receiver-root");
  let credentials=null,deliveries=[],selected=null,connection="reconnecting",pairing=null,pollTimer=null,subscription=null;
  const esc=(value)=>String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
  const plural=(count,word)=>`${count} ${word}${count===1?"":word==="box"?"es":"s"}`;
  const time=(value)=>value?new Date(value).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}):"—";
  const snapshot=(record)=>record.report_snapshot||{};
  function header(){return `<header class="receiver-head"><div class="receiver-brand"><span>ATLAS</span><h1>COC RECEIVER</h1></div><div class="receiver-status ${connection==="connected"?"":"is-offline"}"><strong>● ${connection==="connected"?"Connected — Ready":connection==="reconnecting"?"Reconnecting…":"Offline"}</strong><small>Office COC Station</small></div></header>`}
  function pairingMarkup(){
    if(!Delivery.getAuthSession())return `<section class="receiver-pair"><span class="receiver-eyebrow">OFFICE COC STATION</span><h1>ATLAS sign-in required</h1><p>Use the Name and password assigned to this office station.</p><button class="receiver-primary" data-action="sign-in">SIGN IN</button></section>`;
    if(!pairing)return `<section class="receiver-pair"><span class="receiver-eyebrow">OFFICE COC STATION</span><h1>Pair this computer</h1><p>This browser needs supervisor approval before it can receive compliance reports.</p><button class="receiver-primary" data-action="start-pairing">Create Pairing Code</button></section>`;
    return `<section class="receiver-pair"><span class="receiver-eyebrow">PAIRING REQUEST</span><h1>Approve on a warehouse phone</h1><p>Workflows → Office COC Receiver</p><div class="receiver-code">${esc(pairing.pairingCode)}</div><div class="receiver-qr">${pairing.qrSvg||`QR token ready`}</div><p>Expires ${time(pairing.expiresAt)}</p><p>${esc(pairing.status||"Waiting for supervisor approval…")}</p></section>`;
  }
  function card(record,recent=false){const snap=snapshot(record);return `<button class="receiver-card" data-action="open" data-id="${esc(record.id)}"><span>${recent?"":`<em class="receiver-new">NEW</em>`}<strong>${esc(snap.invoiceNumber)}</strong><b>${esc(snap.customerName)}</b><small>${esc(snap.ifNumber)}</small><small>${plural((snap.pallets||[]).length,"pallet")} · ${plural((snap.pallets||[]).reduce((sum,pallet)=>sum+(pallet.lots||[]).reduce((n,lot)=>n+Number(lot.cases||0),0),0),"box")}</small><small>${recent?`Completed ${time(record.office_completed_at)}`:`Sent by ${esc(snap.employee||"—")} · ${time(record.sent_at)}`}</small></span><i>${recent?"COMPLETED ✓":"›"}</i></button>`}
  function inboxMarkup(){const active=deliveries.filter(item=>item.status!=="OFFICE_COMPLETED"),recent=deliveries.filter(item=>item.status==="OFFICE_COMPLETED");return `<div class="receiver-shell">${header()}<div class="receiver-main"><h2>INCOMING COCs</h2>${active.length?active.map(item=>card(item)).join(""):`<div class="receiver-empty">No COCs are waiting.</div>`}<h2>RECENTLY COMPLETED</h2>${recent.length?recent.map(item=>card(item,true)).join(""):`<div class="receiver-empty">No recently completed reports.</div>`}</div></div>`}
  function detailMarkup(){const record=selected,snap=snapshot(record);return `<div class="receiver-shell"><button class="receiver-back" data-action="back">‹ COC Inbox</button><section class="receiver-detail"><span class="receiver-eyebrow">${record.status==="OFFICE_COMPLETED"?"COMPLETED":"RECEIVED"}</span><h1>${esc(snap.customerName)}</h1><dl><div><dt>Invoice</dt><dd>${esc(snap.invoiceNumber)}</dd></div><div><dt>IF Number</dt><dd>${esc(snap.ifNumber)}</dd></div><div><dt>Sent by</dt><dd>${esc(snap.employee||"—")} · ${time(record.sent_at)}</dd></div><div><dt>Received</dt><dd>${time(record.received_at)}</dd></div></dl>${(snap.pallets||[]).map(pallet=>`<section class="receiver-pallet"><h3>PALLET ${pallet.number}</h3>${(pallet.lots||[]).map(lot=>`<div class="receiver-lot"><span><strong>${esc(lot.model)}</strong><small>Lot ${esc(lot.lot)}</small></span><b>${plural(Number(lot.cases||0),"box")} · ${(Number(lot.cases||0)*Number(lot.caseQuantity||0)).toLocaleString()} units</b></div>`).join("")}</section>`).join("")}<button class="receiver-primary" data-action="download" data-id="${esc(record.id)}">DOWNLOAD COMPANY COC</button>${record.status==="OFFICE_COMPLETED"?"":`<button class="receiver-primary" data-action="complete" data-id="${esc(record.id)}">MARK COMPLETED ✓</button>`}</section></div>`}
  function render(){root.innerHTML=!credentials?pairingMarkup():selected?detailMarkup():inboxMarkup()}
  async function loadInbox(){if(!credentials)return;try{const next=await Delivery.receiverInbox(credentials);for(const item of next.filter(value=>value.status==="SENT")){await Delivery.acknowledgeDelivery(item.id,credentials)}deliveries=await Delivery.receiverInbox(credentials);connection=navigator.onLine?"connected":"offline";if(selected)selected=deliveries.find(item=>item.id===selected.id)||selected;render()}catch(error){connection=navigator.onLine?"reconnecting":"offline";render()}}
  async function startPairing(){try{pairing=await Delivery.createPairing();render();pollPairing()}catch(error){pairing={status:error.message||"Pairing could not start."};render()}}
  async function pollPairing(){if(!pairing?.pairingSessionId)return;for(let attempt=0;attempt<120&&!credentials;attempt+=1){await new Promise(resolve=>setTimeout(resolve,2500));try{const result=await Delivery.pairingStatus(pairing.pairingSessionId);pairing={...pairing,...result};if(result.status==="PAIRED"){credentials=result.credentials;render();connect();return}render()}catch(error){pairing={...pairing,status:error.message};render();return}}}
  function connect(){clearInterval(pollTimer);subscription?.close?.();subscription=Delivery.subscribeToDeliveries({onChange:loadInbox,onState:(state)=>{connection=state;render()}});pollTimer=setInterval(()=>{Delivery.heartbeat(credentials).catch(()=>{});loadInbox()},15000);loadInbox()}
  root.addEventListener("click",async event=>{const button=event.target.closest("[data-action]");if(!button)return;if(button.dataset.action==="sign-in")window.AtlasAuth?.open?.();if(button.dataset.action==="start-pairing")startPairing();if(button.dataset.action==="open"){selected=deliveries.find(item=>item.id===button.dataset.id)||null;render()}if(button.dataset.action==="back"){selected=null;render()}if(button.dataset.action==="download"){button.disabled=true;try{const workbook=await Delivery.downloadOfficeWorkbook(button.dataset.id,credentials);window.AtlasCocStorage?.downloadBlob(workbook.blob,workbook.fileName)}catch(error){alert(error.message||"The official COC could not be downloaded.")}finally{button.disabled=false}}if(button.dataset.action==="complete"){button.disabled=true;try{await Delivery.markOfficeCompleted(button.dataset.id,credentials);selected=null;await loadInbox()}catch(error){button.disabled=false;alert(error.message||"The report could not be completed.")}}});
  window.addEventListener("atlas-auth-changed",async()=>{credentials=null;const verified=await Delivery.verifyReceiver().catch(()=>({paired:false}));credentials=verified.paired?verified.credentials:null;render();if(credentials)connect()});
  window.addEventListener("online",connect);window.addEventListener("offline",()=>{connection="offline";render()});
  (async()=>{const verified=await Delivery.verifyReceiver().catch(()=>({paired:false}));credentials=verified.paired?verified.credentials:null;render();if(credentials)connect()})();
})();
