steps:
  - name: gcr.io/cloud-builders/docker
    args: [build, --file=cloud-run/atlas-routing-scanner/Dockerfile, --tag=us-central1-docker.pkg.dev/$PROJECT_ID/atlas-routing-preview/scanner:$_REVIEW_TAG, .]
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/atlas-routing-preview/scanner:$_REVIEW_TAG
timeout: 600s
options:
  logging: CLOUD_LOGGING_ONLY
