const test=require('node:test');
const assert=require('node:assert/strict');
const {reconcile,watchDay}=require('../atlas-routing-storage.js');
const doc=()=>({date:'2026-09-24',orders:[{id:'a',orderNumber:'SO-1',customer:'A',lines:[{sku:'SKU',caseQty:20}]}],settings:{target:11},lockedTrips:[{id:'sent'}],assignments:{0:'Bubba:truck'}});
test('clean remote edits/deletes retain authoritative locked trips',()=>{const base=doc(),remote={...doc(),orders:[]};const r=reconcile(base,base,remote,false);assert.equal(r.kind,'replace');assert.deepEqual(r.document.lockedTrips,remote.lockedTrips);});
test('dirty append merges preserve local edits, order and settings',()=>{const base=doc(),local=doc(),remote=doc();local.orders[0].customer='Edited';local.settings.target=12;remote.orders.push({id:'b',orderNumber:'SO-2'});const r=reconcile(base,local,remote,true);assert.equal(r.kind,'merge');assert.equal(r.document.orders[0].customer,'Edited');assert.equal(r.document.settings.target,12);assert.equal(r.added.length,1);assert.deepEqual(r.document.lockedTrips,local.lockedTrips);});
test('dirty remote modifications, deletion, duplicate SO or identity conflict never overwrite',()=>{for(const alter of [r=>r.orders[0].customer='Remote',r=>r.orders=[],r=>r.settings.target=9,r=>r.orders.push({id:'b',orderNumber:' so-1 '})]){const base=doc(),remote=doc();alter(remote);assert.equal(reconcile(base,base,remote,true).kind,'conflict');}});
function fixture(){let ctx='CA:user:day1',busy=false,revision=4,remote=doc(),release=null,fail=false;let timer,delay,requests=0,applied=[],signal;const watcher=watchDay({context:()=>ctx,busy:()=>busy,load:async s=>{requests++;signal=s;if(release)await new Promise(r=>release=r);if(fail)throw Error('network');return {revision,document:remote};},apply:r=>applied.push(r),schedule:(fn,ms)=>{timer=fn;delay=ms;return 1;},cancel:()=>{timer=null;}});return {watcher,setContext:v=>ctx=v,setBusy:v=>busy=v,setRevision:v=>revision=v,setFail:v=>fail=v,get requests(){return requests;},get signal(){return signal;},get applied(){return applied;},get delay(){return delay;},tick:()=>timer?.(),hold:()=>{release=true;},release:()=>{const r=release;release=null;r();}};}
test('visible watcher refreshes in two seconds, retries network failures, stops hidden',async()=>{const f=fixture();await f.watcher.check();assert.equal(f.delay,2000);f.setRevision(5);await f.tick();assert.equal(f.applied.at(-1).revision,5);f.setFail(true);await f.tick();assert.equal(f.applied.length,2);f.setFail(false);await f.tick();assert.equal(f.applied.length,3);f.setContext(null);await f.watcher.check();const before=f.requests;await f.tick();assert.equal(f.requests,before);f.setContext('CA:user:day1');await f.watcher.check();assert.equal(f.requests,before+1);});
test('busy state and busy response defer application',async()=>{const f=fixture();f.setBusy(true);await f.watcher.check();assert.equal(f.requests,0);f.setBusy(false);f.hold();const work=f.watcher.check();f.setBusy(true);f.release();await work;assert.equal(f.applied.length,0);f.setBusy(false);await f.watcher.check();assert.equal(f.applied.length,1);});
test('date/account/warehouse changes abort and discard old responses',async()=>{for(const next of ['CA:user:day2','CA:other:day1','TX:user:day1',null]){const f=fixture();f.hold();const old=f.watcher.check();const signal=f.signal;f.setContext(next);f.watcher.stop();assert.equal(signal.aborted,true);f.release();await old;assert.equal(f.applied.length,0);}});
const vm=require('node:vm'),fs=require('node:fs');
test('incoming-order toast is accessible, consolidated and removed at 2000ms',()=>{const source=fs.readFileSync('atlas-routing.js','utf8');const start=source.indexOf('  function showIncomingOrders('),end=source.indexOf('  const liveDay',start);let toast=null,callback,delay;const context={liveToastTimer:null,clearTimeout(){},setTimeout:(fn,ms)=>{callback=fn;delay=ms;},find:()=>toast,document:{createElement:()=>({dataset:{},setAttribute(k,v){this[k]=v;},remove(){toast=null;}}),getElementById:()=>({append:n=>toast=n})}};vm.createContext(context);vm.runInContext(source.slice(start,end)+';showIncomingOrders([{customer:"Customer",orderNumber:"SO-1"}]);',context);assert.equal(delay,2000);assert.equal(toast.role,'status');assert.equal(toast['aria-live'],'polite');assert.match(toast.textContent,/New order added/);callback();assert.equal(toast,null);vm.runInContext('showIncomingOrders([{},{},{}]);',context);assert.equal(toast.textContent,'3 new orders added');});
test('host navigation commits canonical workflow route without a visible shortcut and cleans up',async()=>{const html=fs.readFileSync('index.html','utf8');const start=html.indexOf('        (0, C.useEffect)(() => {\n          const pending = new Set();');assert.ok(start>0);const end=html.indexOf('        function ne(e)',start);let cleanup,observer,timeout,mounted=false,selected;const window={};const context={window,Set,Promise,Error,clearTimeout(){},setTimeout:fn=>timeout=fn,document:{getElementById:id=>id==='atlas-coc-workflows-root'&&mounted?{}:null,body:{}},MutationObserver:class{constructor(fn){observer=fn;}observe(){}disconnect(){}},atlasReturnToSectionRoot:key=>selected=key,C:{useEffect:fn=>cleanup=fn()}};vm.runInNewContext(html.slice(start,end),context);let done=false;const opened=window.AtlasNavigation.openSection('workflows').then(()=>done=true);assert.equal(selected,'workflows');await Promise.resolve();assert.equal(done,false);mounted=true;observer();await opened;assert.equal(done,true);mounted=false;const failed=window.AtlasNavigation.openSection('workflows');timeout();await assert.rejects(failed,/Navigation ended/);cleanup();assert.equal(window.AtlasNavigation,undefined);assert.ok(html.includes('atlasScannerShortcut'));});
