const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'../atlas-dashboard.js'),'utf8');
const warehouses=[{id:'00000000-0000-4000-8000-000000000001',code:'CA',active:true},{id:'00000000-0000-4000-8000-000000000002',code:'TX',active:true}];
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return{promise,resolve,reject}};
function fixture(){
 const events={},storage=new Map(),requests=[];let responder=()=>undefined,actor={access_token:'synthetic-A',user:{id:'A',app_metadata:{role:'admin',home_warehouse_code:'CA'}}};
 const document={documentElement:{scrollTop:0},addEventListener(){},querySelector:()=>null,getElementById:()=>null};
 const window={document,addEventListener:(n,fn)=>events[n]=fn,scrollTo(){},setTimeout(){},clearTimeout(){},setInterval(){},clearInterval(){},AtlasAuth:{getSession:()=>actor,getValidSession:async()=>actor},AtlasCocDelivery:{requestedWarehouseCode:()=>actor?.user.app_metadata.home_warehouse_code||'CA',warehouseContext:async({warehouseCode}={})=>({profile:{userId:actor.user.id,role:'admin'},accessibleWarehouses:warehouses,selectedWarehouse:warehouses.find(w=>w.code===warehouseCode)||warehouses[0]})}};
 const fetch=async(url,options={})=>{const body=options.body?JSON.parse(options.body):{};requests.push({url,body});const override=await responder(url,body);return{ok:true,status:200,json:async()=>override??(url.includes('/profiles?')?[{user_id:actor?.user.id,role:'admin'}]:url.includes('/rest/')?[]:body.action==='list'?{deliveries:[],total:0}:body.action==='list-edits'?{edits:[]}:{}),blob:async()=>new Blob(['synthetic'])};};
 vm.runInNewContext(source.replace('window.atlasOpenDashboard = openDashboard;', 'window.testApi={state,loadData,loadCocData,loadScannerData,loadCocWorkbook,cocWorkbookCache,readTable,rememberCocEdit,readSeenCocEditIds,handleChange,api,openDashboardCocPreview,downloadDashboardCoc,loadScannerCorrection};'),{window,document,fetch,MutationObserver:class{observe(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},sessionStorage:{getItem:()=>null},Intl,URL,Date,console,Map,Set,Blob});
 const api=window.testApi;Object.assign(api.state,{session:actor,currentProfile:{role:'admin'},selectedWarehouse:warehouses[0],warehouses,cocPeriod:'all'});
 return{...api,window,events,requests,storage,respond(fn){responder=fn},auth(id,home='CA'){actor=id?{access_token:'synthetic-'+id,user:{id,app_metadata:{role:'admin',home_warehouse_code:home}}}:null;events['atlas-auth-changed']({detail:{session:actor}});},switch(code){api.handleChange({target:{value:code,matches:s=>s==='[data-warehouse-selector]',closest:()=>null}});}};
}
const drain=async()=>{for(let i=0;i<40;i++)await Promise.resolve()};
test('account change immediately clears old selection and operational state while closed',()=>{const f=fixture();f.state.selectedWarehouse=warehouses[1];f.state.cocRecords=[{id:'old'}];f.state.history=[{id:'old'}];f.auth('B');assert.equal(f.state.selectedWarehouse,null);assert.equal(f.state.cocRecords.length,0);assert.equal(f.state.history.length,0)});
test('late COC response cannot populate a different account in the same warehouse',async()=>{const f=fixture(),g=deferred();f.respond((u,b)=>b.action==='list'?g.promise:undefined);const pending=f.loadCocData();await drain();f.auth('B');f.state.selectedWarehouse=warehouses[0];f.state.currentProfile={role:'admin'};g.resolve({deliveries:[{id:'old',status:'SENT'}],total:1});await pending;assert.equal(f.state.cocRecords.length,0);assert.equal(f.state.cocLoaded,false)});
test('delayed CA edit alerts cannot overwrite completed TX load',async()=>{const f=fixture(),g=deferred();f.respond((u,b)=>b.action==='list-edits'?(b.warehouseCode==='CA'?g.promise:{edits:[{id:'TX'}]}):undefined);const old=f.loadData();await drain();await f.loadData({force:true,warehouseCode:'TX'});g.resolve({edits:[{id:'CA'}]});await old;assert.equal(f.state.selectedWarehouse.code,'TX');assert.equal(f.state.cocEditAlerts[0].id,'TX')});
test('missing warehouse module and ID never send unfiltered warehouse reads',async()=>{const f=fixture();delete f.window.AtlasCocDelivery;f.state.selectedWarehouse=null;await f.loadData();assert.equal(f.requests.filter(r=>/locations\?/.test(r.url)).length,0);await assert.rejects(f.readTable('locations','synthetic',{warehouse:true,warehouseId:null}));assert.equal(f.state.selectedWarehouse,null)});
test('workbook cache and notification read state belong to account and warehouse',async()=>{const f=fixture();f.cocWorkbookCache.set('delivery',{blob:'old'});f.rememberCocEdit('edit');f.auth('B');f.state.selectedWarehouse=warehouses[0];f.state.currentProfile={role:'admin'};assert.equal(f.readSeenCocEditIds().length,0);assert.equal(f.cocWorkbookCache.size,0)});
module.exports={fixture,warehouses,deferred,drain};

for (const family of ['coc','scanner']) for (const rejected of [false,true]) test(family+' delayed '+(rejected?'failure':'success')+' cannot survive account A-B-A',async()=>{
 const f=fixture(),g=deferred();f.respond((u,b)=>b.action==='metrics'?g.promise:undefined);
 const pending=family==='coc'?f.loadCocData():f.loadScannerData();await drain();f.auth('B');f.auth('A');f.state.selectedWarehouse=warehouses[0];f.state.currentProfile={role:'admin'};
 f.state.cocLoading=true;f.state.scannerLoading=true;
 if(rejected)g.reject(new Error('old failure'));else g.resolve({summary:{secret:'old'},total:99});await pending;
 assert.equal(f.state.cocRecords.length,0);assert.equal(f.state.scannerData,null);assert.equal(f.state.cocError,'');assert.equal(f.state.scannerError,'');assert.equal(f.state.cocLoading,true);assert.equal(f.state.scannerLoading,true);
});
test('delayed warehouse A-B-A response cannot replace newest COC records',async()=>{const f=fixture(),g=deferred();let old=true;f.respond((u,b)=>b.action==='list'&&old?g.promise:undefined);const pending=f.loadCocData();await drain();old=false;await f.loadData({force:true,warehouseCode:'TX'});await f.loadData({force:true,warehouseCode:'CA'});f.state.cocRecords=[{id:'new'}];g.resolve({deliveries:[{id:'old'}],total:1});await pending;assert.equal(f.state.cocRecords[0].id,'new')});
test('workbook response cannot refill cache after account transition',async()=>{const f=fixture(),g=deferred();f.respond((u,b)=>b.action==='download-workbook'?g.promise:undefined);const pending=f.loadCocWorkbook('old');await drain();f.auth('B');f.state.selectedWarehouse=warehouses[0];g.resolve({downloadUrl:'https://fixture.invalid/old'});await assert.rejects(pending,/CONTEXT_CHANGED/);assert.equal(f.cocWorkbookCache.size,0);assert.equal(f.requests.some(r=>r.url==='https://fixture.invalid/old'),false)});
test('token refresh never retries old request under a new account',async()=>{const f=fixture(),g=deferred();f.window.AtlasAuth.getValidSession=()=>g.promise;const pending=f.api('/rest/v1/locations');f.auth('B');g.resolve(f.state.session);await assert.rejects(pending,/CONTEXT_CHANGED/);assert.equal(f.requests.length,0)});
test('same-account token refresh preserves current state and requests',async()=>{const f=fixture();f.state.cocRecords=[{id:'keep'}];f.auth('A');assert.equal(f.state.cocRecords[0].id,'keep');await f.loadData();assert.equal(f.state.error,'')});
test('two manager instances keep independent selections and can each switch',async()=>{const a=fixture(),b=fixture();await Promise.all([a.loadData({warehouseCode:'CA'}),b.loadData({warehouseCode:'TX'})]);assert.equal(a.state.selectedWarehouse.code,'CA');assert.equal(b.state.selectedWarehouse.code,'TX');await a.loadData({force:true,warehouseCode:'TX'});assert.equal(b.state.selectedWarehouse.code,'TX');await b.loadData({force:true,warehouseCode:'CA'});assert.equal(a.state.selectedWarehouse.code,'TX');assert.equal(b.state.selectedWarehouse.code,'CA')});
for(const kind of ['missing-id','mismatch','membership','failure'])test('invalid warehouse context fails closed: '+kind,async()=>{const f=fixture();f.window.AtlasCocDelivery.warehouseContext=async()=>{if(kind==='failure')throw Error('WAREHOUSE_ACCESS_DENIED');return{selectedWarehouse:kind==='missing-id'?{code:'CA'}:warehouses[1],accessibleWarehouses:kind==='membership'?[]:warehouses}};await f.loadData({force:true,warehouseCode:'CA'});assert.equal(f.requests.length,0);assert.equal(f.state.selectedWarehouse,null);assert.ok(f.state.error||f.state.accessRequired)});
test('notification read state is separate in CA and TX for the same account',()=>{const f=fixture();f.rememberCocEdit('same-id');f.state.selectedWarehouse=warehouses[1];assert.equal(f.readSeenCocEditIds().length,0);f.state.selectedWarehouse=warehouses[0];assert.equal(f.readSeenCocEditIds()[0],'same-id')});
