const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {stripTypeScriptTypes}=require('node:module');
const proposal=path.join(__dirname,'../supabase/proposals/ca-tx-dashboard-isolation');
const source=stripTypeScriptTypes(fs.readFileSync(path.join(proposal,'scanner-intelligence.proposed.ts'),'utf8')).replace(/^import .*;\n/,'');
function fixture({role='admin',claim=role,codes=['CA','TX'],fail=false}={}){let handler;const user={id:'synthetic',app_metadata:{role:claim,home_warehouse_code:'CA'}};const filters=[];const client={auth:{getUser:async()=>({data:{user}})},from(table){const q={};for(const method of ['select','eq','in','gte','lte','order','range'])q[method]=(...args)=>{filters.push([table,method,...args]);return q};const result=()=>({error:fail&&table==='profile_warehouse_access'?new Error('synthetic unavailable'):null,data:table==='profiles'?{role,warehouse_id:'CA'}:table==='profile_warehouse_access'?codes.map(warehouse_id=>({warehouse_id})):table==='warehouses'?codes.map(code=>({id:code,code})):[]});q.maybeSingle=async()=>result();q.then=(resolve,reject)=>Promise.resolve(result()).then(resolve,reject);return q;}};vm.runInNewContext(source,{createClient:()=>client,Deno:{env:{get:()=> 'synthetic'},serve:fn=>handler=fn},Response,console:{error(){}},Uint8Array,atob});return{filters,call:warehouseCode=>handler(new Request('https://fixture.invalid',{method:'POST',headers:{Authorization:'Bearer synthetic','Content-Type':'application/json'},body:JSON.stringify({action:'metrics',warehouseCode})}))};}
test('proposed scanner membership checks preserve dual administrators and narrow ALL',async()=>{for(const code of ['CA','TX','ALL']){const f=fixture(),r=await f.call(code);assert.equal(r.status,200);}const f=fixture({codes:['CA']});assert.equal((await f.call('TX')).status,403);assert.equal((await f.call('ALL')).status,200);assert.ok(f.filters.some(a=>a[0]==='coc_scanner_attempts'&&a[1]==='eq'&&a[2]==='warehouse_code'&&a[3]==='CA'));});
test('proposed scanner denies removed membership, stale admin role and lookup failure',async()=>{assert.equal((await fixture({codes:[]}).call('CA')).status,403);assert.equal((await fixture({role:'picker',claim:'admin'}).call('CA')).status,403);assert.equal((await fixture({fail:true}).call('CA')).status,500);});

test('proposed restrictive boundaries and grant revocations run against isolated PostgreSQL',async t=>{
 const {PGlite}=require('@electric-sql/pglite');const db=new PGlite();t.after(()=>db.close());
 const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,ca=id(1),tx=id(2),actors=[['picker',ca],['supervisor',ca],['supervisor',tx],['admin',ca],['admin',tx],['office_receiver',tx]];
 const meta=JSON.parse(fs.readFileSync(path.join(proposal,'live-metadata.json'),'utf8'));
 const rows=key=>JSON.parse(JSON.parse(meta[key].content[0].text).result.match(/<untrusted-data-[^>]+>\n([\s\S]*?)\n<\/untrusted-data-/)[1]);
 await db.exec(`create role anon;create role authenticated;create schema auth;grant usage on schema public,auth to anon,authenticated;create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create type app_role as enum('picker','supervisor','admin','office_receiver');create table auth.users(id uuid primary key,deleted_at timestamptz,banned_until timestamptz);create table warehouses(id uuid primary key,code text,active boolean default true);create table profiles(user_id uuid primary key,role app_role,warehouse_id uuid);create table profile_warehouse_access(user_id uuid,warehouse_id uuid);create table skus(id uuid primary key,active boolean);create table locations(id uuid,warehouse_id uuid,sku_id uuid);`);
 for(const name of ['atlas_undo_snapshots','inventory_activity','location_history','sku_delete_requests','coc_model_case_quantities','coc_delivery_events','coc_stations','coc_deliveries'])await db.exec(`create table ${name}(id uuid,warehouse_id uuid);`);
 await db.exec(`insert into warehouses values('${ca}','CA',true),('${tx}','TX',true);insert into skus values('${id(3)}',true);insert into locations values('${id(4)}','${ca}','${id(3)}'),('${id(5)}','${tx}','${id(3)}');insert into atlas_undo_snapshots values('${id(6)}','${ca}'),('${id(7)}','${tx}');`);
 for(let i=0;i<actors.length;i++){const [role,home]=actors[i],user=id(10+i);await db.exec(`insert into auth.users(id) values('${user}');insert into profiles values('${user}','${role}','${home}');insert into profile_warehouse_access values('${user}','${home}');`);if(role==='admin')await db.exec(`insert into profile_warehouse_access values('${user}','${home===ca?tx:ca}');`);}
 for(const helper of rows('helpers'))await db.exec(helper.definition);
 for(const table of ['profiles','locations','atlas_undo_snapshots','inventory_activity','location_history','sku_delete_requests'])await db.exec(`alter table ${table} enable row level security;`);
 const ident=x=>'"'+x.replaceAll('"','""')+'"';for(const p of rows('policies'))await db.exec(`create policy ${ident(p.policyname)} on ${ident(p.tablename)} as ${p.permissive} for ${p.cmd} to ${p.roles.slice(1,-1)} ${p.qual?'using ('+p.qual+')':''} ${p.with_check?'with check ('+p.with_check+')':''};`);
 await db.exec('grant select on profiles,locations,atlas_undo_snapshots,inventory_activity,location_history,skus to authenticated;grant select on locations,skus to anon;grant insert,update,delete on locations to authenticated;');
 for(const g of rows('grants').filter(g=>['coc_model_case_quantities','coc_delivery_events','coc_stations','sku_delete_requests','atlas_undo_snapshots','coc_deliveries'].includes(g.table_name)))await db.exec(`grant ${g.privilege_type} on ${g.table_name} to ${g.grantee}`);
 const as=async(index,query)=>{await db.exec(`set role ${index===null?'anon':'authenticated'};select set_config('request.jwt.claim.sub','${index===null?'':id(10+index)}',false)`);try{return(await db.query(query)).rows}finally{await db.exec('reset role')}};
 assert.equal((await as(1,'select * from profiles')).length,6,'baseline broad profile policy reproduced');assert.equal((await as(1,'select * from atlas_undo_snapshots')).length,2);
 await db.exec(fs.readFileSync(path.join(proposal,'proposed-up.sql'),'utf8'));
 assert.equal((await as(null,'select * from locations')).length,2,'approved public lookup unchanged');
 for(let i=0;i<actors.length;i++){const [role,home]=actors[i],admin=role==='admin';const loc=await as(i,'select * from locations');assert.equal(loc.length,admin?2:1);if(!admin)assert.equal(loc[0].warehouse_id,home);const profiles=await as(i,'select * from profiles');assert.equal(profiles.length,admin?6:role==='supervisor'?3:1);const undo=await as(i,'select * from atlas_undo_snapshots');assert.equal(undo.length,admin?2:role==='supervisor'?1:0);}
 assert.equal((await as(1,`update locations set sku_id=sku_id where warehouse_id='${tx}' returning id`)).length,0);
 assert.equal((await as(1,`update locations set sku_id=sku_id where warehouse_id='${ca}' returning id`)).length,1);
 await assert.rejects(as(1,`insert into locations values('${id(90)}','${tx}','${id(3)}')`),/row-level security/);
 assert.equal((await db.query("select has_table_privilege('authenticated','sku_delete_requests','SELECT') as permitted")).rows[0].permitted,false);
 for(const role of ['anon','authenticated'])for(const privilege of ['TRUNCATE','TRIGGER','REFERENCES'])assert.equal((await db.query(`select has_table_privilege('${role}','coc_deliveries','${privilege}') as permitted`)).rows[0].permitted,false);
 await db.exec(fs.readFileSync(path.join(proposal,'proposed-rollback.sql'),'utf8'));assert.equal((await as(1,'select * from profiles')).length,6);assert.equal((await db.query("select has_table_privilege('authenticated','coc_deliveries','TRUNCATE') as permitted")).rows[0].permitted,true);
});
