const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),os=require('node:os');
const {chromium}=require(process.env.ATLAS_PLAYWRIGHT_PATH||path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
test('assigned Home card opens scoped mobile stops and revocation returns Home',async t=>{
 const server=http.createServer((req,res)=>res.end('<div id="atlas-assigned-trips"></div><section data-driver-mode="true"><div id="pods"></div></section>'));await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));
 const browser=await chromium.launch({executablePath:process.env.ATLAS_BROWSER_PATH||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:'+server.address().port);
 await page.evaluate(()=>{
  const user={id:'00000000-0000-4000-8000-000000000012'};window.AtlasAuth={getSession:()=>({user}),getValidSession:async()=>({user,access_token:'synthetic'})};window.AtlasCocDelivery={requestedWarehouseCode:()=> 'CA'};window.AtlasNavigation={open:action=>window.navigated=action};window.atlasSupabaseConfig={key:'synthetic'};window.calls=[];
  const stop={id:'00000000-0000-4000-8000-000000000030',customer:'TEST CUSTOMER — DO NOT DELIVER',sales_order:'SO-TEST-0001',address:'123 TEST STREET',workflow:'assigned-trip',is_test:true,trip_index:0,trip_version:1,current:true,status:'pending',warehouse_id:'00000000-0000-4000-8000-000000000001',driver_name:'Test driver',source_assignment:'Test driver:truck',shipment_number:1,shipment_total:1,source_shipment:{palletSpaces:2,boxAllocation:[{sku:'TEST',boxes:20}]},delivery:{signatureRequired:true},submission:null};
  window.fetch=async(url,opts)=>{const body=JSON.parse(opts.body);calls.push({url,body});if(url.endsWith('atlas_driver_stop_action'))return new Response(JSON.stringify({message:'DRIVER_ACCESS_DENIED'}),{status:403});if(url.endsWith('/delivery-pod'))return new Response(JSON.stringify({capability:'driver',shipments:[stop],email_enabled:false}));return new Response(JSON.stringify(url.endsWith('my_trips')?{trips:[{id:'00000000-0000-4000-8000-000000000020',tripIndex:0,vehicleId:'box_truck',isTest:true,status:'assigned',stops:[stop]}]}:{}));};
 });
 for(const name of ['atlas-routing-assignment.js','atlas-routing-pod-core.js','atlas-routing-pod-queue.js','atlas-routing-pod.js','atlas-driver-workspace.js'])await page.addScriptTag({content:fs.readFileSync(path.join(__dirname,'..',name),'utf8')});
 await page.evaluate(()=>{atlasRoutingPOD.configure({enabled:true});atlasRoutingPOD.mount(document.getElementById('pods'),()=> '2026-09-22');window.atlasOpenRouting=()=>atlasRoutingPOD.load();});
 await page.locator('[data-assigned-trip]').click();await page.locator('[data-pod-trip]').first().click();await page.locator('[data-driver-signature]').waitFor();assert.equal(await page.locator('a[href*="google.com/maps"]').count(),0);assert.equal(await page.locator('[data-driver-complete]').isDisabled(),true);
 assert.equal(await page.evaluate(()=>calls.find(c=>c.body.action==='list').body.driverOnly),true);await page.locator('[data-driver-arrived]').click();await page.waitForFunction(()=>window.navigated==='home');assert.deepEqual(errors,[]);
});
